CLASS LHC_ZR_MM_PRG_PAY_PYMT DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ProgressPaymentSpotPayment
        RESULT result.
ENDCLASS.

CLASS LHC_ZR_MM_PRG_PAY_PYMT IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
ENDCLASS.
